[package]
name = "usage_examples"
version = "0.1.0"
edition = "2024"

[dependencies]
mycelium_computing = { path = "../core" }
dust_dds =  { git = "https://github.com/s2e-systems/dust-dds.git", branch = "main" }
rand = "0.10.0-rc.5"
smol = "2.0.2"
